# -*- coding: utf-8 -*-
"""Telco_churn_customer_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVxP55SG6F7Cx2E-ahLB16-3ykQnlvWO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_excel("Telco_customer_churn.xlsx")
df.head()

df.isnull().sum()
df.drop_duplicates(inplace=True)

"""Churn Distribution"""

sns.countplot(x='Churn Label', data=df)
plt.title("Customer Churn Distribution")
plt.show()

"""Contract vs Churn"""

sns.countplot(x='Contract', hue='Churn Label', data=df)
plt.title("Contract Type vs Churn")
plt.show()

"""Monthly charges vs Churn"""

sns.boxplot(x='Churn Label', y='Monthly Charges', data=df)
plt.show()

"""Tenure vs Churn"""

sns.boxplot(x='Churn Label', y='Tenure Months', data=df)
plt.title("Tenure vs Churn")
plt.show()

"""Internet service vs Churn"""

sns.countplot(x='Internet Service', hue='Churn Label', data=df)
plt.title("Internet Service vs Churn")
plt.show()

"""Payment method vs Churn"""

sns.countplot(x='Payment Method', hue='Churn Label', data=df)
plt.xticks(rotation=40)
plt.title("Payment Method vs Churn")
plt.show()

"""Correlation Heatmap"""

plt.figure(figsize=(10, 8))
sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()













